spring:
  application:
    name: "axon-gateway"

#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: false
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQL95Dialect
#        default_schema: "public"
#        jdbc:
#          lob:
#            non_contextual_creation: true
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    username: "event_sourcing_user"
#    password: "1234567"
#    url: "jdbc:postgresql://localhost:5432/event_sourcing_db"

axon:
  serializer:
    general: jackson
    events: jackson
    messages: jackson